#!/bin/sh

# Error messages
choice_error_title='Invalid Choice'
choice_error_message='is an invalid choice. Halting.'

# Cancel messages
choice_cancel_title='Operation Cancelled'
choice_cancel_message='No screenshot will be taken. Halting.'

# Flags (must be set)
screenshot_flags=''

# Exit handler (exit status, stdout, stderr, notifications)
exit_handler () {
	exit_code=$1
	notification_title="$2"
	message="$3"
	notify_opts=' '
	if [ "${exit_code}" -gt 0 ]; then
		notify_opts='--urgency=critical'
		echo "${message}" 1>&2
	else
		echo "${message}"
	fi
	shift 3
	notify-send $notify_opts "${notification_title}" "${*:-$message}"
	exit "$exit_code"
}

# Screenshot types
dmenu_type_full="full (all screens)"
dmenu_type_screen="screen (the current active screeen)"
dmenu_type_window="window (the current active window)"
dmenu_type_select="select interactively (draw a rectangle with the mouse)"

# Concatenate options
dmenu_options="${dmenu_type_full}\n${dmenu_type_screen}\n${dmenu_type_window}\n${dmenu_type_select}"

# Pick a screenshot type with dmenu
dmenu_type_pick="$(printf "%s${dmenu_options}" | dmenu -l 6 -i -p "Screenshot which area?")"
case "$dmenu_type_pick" in
	"$dmenu_type_full") screenshot_type='full' ;;
	"$dmenu_type_screen") screenshot_type='screen' ;;
	"$dmenu_type_window") screenshot_type='window' ;;
	"$dmenu_type_select")
		screenshot_type='select'
		screenshot_flags='-bd'
		;;
	*) exit_handler 1 "$choice_error_title" "'$dmenu_type_pick' $choice_error_message" ;;
esac

# Choose whether to capture background when relevant
case "$screenshot_type" in
	window)
		capture_background="$(printf "yes\nno" | dmenu -i -p "Capture window background?")"
		case "$capture_background" in
			yes) screenshot_flags="${screenshot_flags} -b" ;;
			no) ;;
			*) exit_handler 1 "$choice_error_title" "'$capture_background' $choice_error_message" ;;
		esac
		;;
esac

# Choose to show or hide the cursor
case "$screenshot_type" in
	full|screen|window)
		show_cursor="$(printf "show\nhide" | dmenu -i -p "Show the cursor or hide it?")"
		case "$show_cursor" in
			show) ;;
			hide) screenshot_flags="${screenshot_flags} -c" ;;
			*) exit_handler 1 "$choice_error_title" "'$show_cursor' $choice_error_message" ;;
		esac
		;;
esac

screenshot ${screenshot_flags} -n "$screenshot_type"
