#!/bin/sh

# Get a menu of characters to copy.

# Check if the characters directory exists.
characters_directory="${XDG_DATA_HOME:-$HOME/.local/share}"/personal/chars
if ! [ -d "$characters_directory" ] || ! [ -r "$characters_directory" ] || ! [ -x "$characters_directory" ]; then
	notify-send "Error" "$characters_directory is not properly configured."
	exit 1
fi

# Get user selection via dmenu from emoji file.
chosen=$(cut -d ';' -f1 "$characters_directory"/* | dmenu -i -l 30 | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

# Copy the character to the clipboard and show a confirmation notification.
printf "%s" "$chosen" | xclip -selection clipboard
notify-send "'$chosen' copied to clipboard."
