#!/bin/sh

# Get a menu of characters to copy.

# Check if the characters directory exists.
if ! [ -d "${XDG_DATA_HOME:-$HOME/.local/share}"/personal/chars ] || ! [ -r "${XDG_DATA_HOME:-$HOME/.local/share}"/personal/chars ] || ! [ -x "${XDG_DATA_HOME:-$HOME/.local/share}"/personal/chars ]; then
	notify-send "Error" "${XDG_DATA_HOME:-$HOME/.local/share}/personal/chars is not properly configured."
	exit 1
fi

# Get user selection via dmenu from emoji file.
chosen=$(cut -d ';' -f1 "${XDG_DATA_HOME:-$HOME/.local/share}"/personal/chars/* | dmenu -i -l 30 | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

# Copy the character to the clipboard and show a confirmation notification.
printf "%s" "$chosen" | xclip -selection clipboard
notify-send "'$chosen' copied to clipboard."
