#!/bin/sh

# Aliases
alias notify-send='notify-send --urgency=critical'

# Error messages
choice_error_message='is an invalid choice. Halting.'

# Flags (must be set)
screenshot_flags=''

# Screenshot types
dmenu_type_full="full (all screens)"
dmenu_type_screen="screen (the current active screeen)"
dmenu_type_window="window (the current active window)"
dmenu_type_select="select interactively (draw a rectangle with the mouse)"

# Concatenate options
dmenu_options="${dmenu_type_full}\n${dmenu_type_screen}\n${dmenu_type_window}\n${dmenu_type_select}"

# Pick a screenshot type with dmenu
dmenu_type_pick="$(printf "%s${dmenu_options}" | dmenu -l 6 -i -p "Screenshot which area?")"
case "$dmenu_type_pick" in
	"$dmenu_type_full") screenshot_type='full' ;;
	"$dmenu_type_screen") screenshot_type='screen' ;;
	"$dmenu_type_window") screenshot_type='window' ;;
	"$dmenu_type_select")
		screenshot_type='select'
		screenshot_flags='-bd'
		;;
	*)
		notify-send "Error" "'$dmenu_type_pick' $choice_error_message"
		exit 1
		;;
esac

# Choose whether to capture background when relevant
case "$screenshot_type" in
	window)
		capture_background="$(printf "yes\nno" | dmenu -i -p "Capture window background?")"
		case "$capture_background" in
			yes)
				screenshot_flags="${screenshot_flags} -b"
				;;
			no) ;;
			*)
				notify-send "Error" "'$capture_background' $choice_error_message"
				exit 1
				;;
		esac
		;;
esac

# Choose to show or hide the cursor
case "$screenshot_type" in
	full|screen|window)
		show_cursor="$(printf "show\nhide" | dmenu -i -p "Show the cursor or hide it?")"
		case "$show_cursor" in
			show) ;;
			hide)
				screenshot_flags="${screenshot_flags} -c"
				;;
			*)
				notify-send "Error" "'$show_cursor' $choice_error_message"
				exit 1
				;;
		esac
		;;
esac

screenshot ${screenshot_flags} -n "$screenshot_type"
