#!/bin/sh

# Get a menu of characters to copy.

# Characters directory
characters_directory="${XDG_DATA_HOME:-$HOME/.local/share}"/personal/chars

# Error messages
directory_error_message="$characters_directory is not properly configured."

# Check if the characters directory exists.
if ! [ -d "$characters_directory" ] || ! [ -r "$characters_directory" ] || ! [ -x "$characters_directory" ]; then
	notify-send "Error" "$directory_error_message"
	echo "$directory_error_message" 1>&2
	exit 1
fi

# Get user selection via dmenu from emoji file.
chosen=$(cut -d ';' -f1 "$characters_directory"/* | dmenu -i -l 30 | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit 0

# Type and copy the character to the clipboard and show a confirmation notification.
xdotool type "$chosen"
printf "%s" "$chosen" | xclip -selection clipboard
notify-send "'$chosen' copied to clipboard."
