#!/bin/sh

# Set the right default permissions for files
umask 077

# Aliases
alias notify-send='notify-send --urgency=critical'

# Directory where screenshots are saved
screenshots_directory="$HOME"/pictures/screenshots

# Notifications (default none)
notifications=0

# Error messages
directory_error_message="$screenshots_directory is not properly configured. Halting."
flag_error_message="contains an invalid flag. Halting."
type_error_message="is an invalid screenshot type. Halting."
screenshot_error_message="Failed to take the screenshot."

# Parse optional flags, save them and remove them from the positional parameters
opts=''
curropt=''
optgroup=''
virtoptgroup=''
while getopts "bcdn" curropt; do
	paramgroup="$1"
	case "$curropt" in
		b)
			flag="--capturebackground"
			;;
		c)
			flag="--hidecursor"
			;;
		d)
			flag="--delay=0.2 --quiet"
			;;
		n)
			notifications=1
			;;
		*)
			[ "$notifications" -eq 1 ] && notify-send "Error" "'${1}' $flag_error_message"
			echo "'${1}' $flag_error_message" 1>&2
			exit 1
			;;
	esac
	virtoptgroup="${virtoptgroup}${curropt}"
	optgroup="${optgroup} ${flag}"
	if [ "-${virtoptgroup}" = "$paramgroup" ]; then
		opts="${opts}${optgroup}"
		shift 1
		virtoptgroup=''
		optgroup=''
	fi
done

# Check the directory where screenshots will be saved exists and has the right permissions
if ! [ -d "$screenshots_directory" ] || ! [ -r "$screenshots_directory" ] || ! [ -w "$screenshots_directory" ] || ! [ -x "$screenshots_directory" ]; then
	[ "$notifications" -eq 1 ] && notify-send "Error" "$directory_error_message"
	echo "$directory_error_message" 1>&2
	exit 1
fi

# Select the screenshot type
case "$1" in
	full)
		opts="${opts} "
		;;
	screen)
		opts="${opts} --window=root"
		;;
	window)
		opts="${opts} --window=$(xdotool getactivewindow)"
		;;
	select)
		opts="${opts} --select --bordersize=3 --color=255,255,255"
		;;
	*)
		[ "$notifications" -eq 1 ] && notify-send "Error" "'${1}' $type_error_message"
		echo "'${1}' $type_error_message" 1>&2
		exit 1
		;;
esac

# Take the screenshot according to selected options
screenshot_name=screenshot-"$(date "+%Y-%m-%d-%H-%M-%S")".png
if maim $opts --format=png --quality 10 "${screenshots_directory}"/"${screenshot_name}"; then
	[ "$notifications" -eq 1 ] && command notify-send "Screenshot saved" "$screenshot_name"
	echo "${screenshots_directory}/${screenshot_name}"
	exit 0
fi

# Notify if screenshot couldn't be taken
[ "$notifications" -eq 1 ] && notify-send "Screenshot NOT saved" "$screenshot_error_message"
echo "$screenshot_error_message" 1>&2
exit 1
